import Header from "@/components/Header";
import "./globals.css";
import { ThemeProvider } from "@/clientSide";
export const metadata = {
  title: "CHAT GPT-4",
  description: "Generated by Amir Whdan",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=" bg-gradient-to-r from-[#022143] to-[#040C18]">
        <ThemeProvider>
          <Header />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
